### ISSUE TITLE
Availability on F-Droid and Play Store

### ISSUE THREAD

**Issue by alexanderadam** [TheWall89/AndrOCR#4]
Hi @TheWall89,

thank you for your work. Somehow the link to the play store is broken and would it be feasible to publish AndrOCR to [F-Droid?](https://f-droid.org/repository/browse/?fdfilter=AndrOCR&fdpage=1&page_id=0)

Thank you!

PS: I have no experience with publishing something there or with Android development.

**Comment by TheWall89** [comment]
Hi @alexanderadam,

I removed the App from the play store because it is old and I have no time to maintain it. I'm sure you can find some valid alternatives to it.

Best wishes.

**Comment by alexanderadam** [comment]
What a pitty but thank you for responding.
